greenspace + refactor
diwise/iot-transform-fiware pull request #28
Opened 2022-11-23 14:37 UTC by nordbergmikael

2022-11-23 15:41 UTC, shestyf commented on internal/pkg/application/transform/transformers.go
> +		ObjectURN: urn:oma:lwm2m:ext:3303
if illuminance exists as its own type, perhaps we ought to add it in here with this comment for the temp and airquality

2022-11-23 15:44 UTC, shestyf commented on internal/pkg/application/transform/transformers.go
> +		//_, err = cbClient.UpdateEntityAttributes(ctx, entityID, fragment, headers)
this should be removed, no?

2022-11-23 15:48 UTC, shestyf commented on internal/pkg/application/transform/transformers.go
> +			// If we failed to update the entity's attributes, we need to create it
check here if the error is that we can't find the entity, as we do it in IndoorEnvironmetObserved above. we've used that same pattern in another service as well. Line 202 onwards.

2022-11-23 15:51 UTC, shestyf commented on internal/pkg/application/transform/transformers.go
> +	// GreenspaceRecord is called by one of its properties. First out creates the entity, all other subsequent calls, independent which property, updates the entity.
I'm a little unsure of what this comment means, but I think it should probably say "GreenspaceRecord is called by one of its properties. First it creates the entity, and on all subsequent calls, independent of which property, it updates the entity."

2022-11-23 15:54 UTC, shestyf commented on internal/pkg/application/transform/transformers_test.go
> +//	- subsequent occuranceses are treated as additional measurements and ignored
sp. of occurance on line 222 - should be singular. "first occurance is treated.."

on line 223, should be occurances.

2022-11-23 15:54 UTC, shestyf commented on internal/pkg/application/transform/transformers_test.go
> +func TestThatGreenspaceRecordIsCreatedIfNonExisting(t *testing.T) {
NonExistant

2022-11-23 15:55 UTC, shestyf requested changes
spelling errors mostly

2022-11-23 17:04 UTC, istyf reviewed
Nothing to add.

2022-11-24 11:01 UTC, istyf approved these changes
/lgtm

2022-11-24 11:42 UTC, shestyf approved these changes
/lgtm

2022-11-24 11:42 UTC, merged